name: "Define terraform parameters"
description: "Defining parameters for terraform"
author: "Mathieu Henrotay"
inputs:
  app_key:
    required: true
    description: "App key to use to build app_url and terraform_workspace"
  github_branch:
    required: true
    description: "Github branch"
outputs:
  doppler_app_service_token_secret:
    description: "Doppler service token secret name"
  trustup_app_key:
    description: "Trustup app key"
  trustup_app_key_suffix:
    description: "Suffix applied to current trustup app key"
  trustup_app_key_suffixed:
    description: "Trustup app key for current environment"
  app_url:
    description: "App url"
  app_environment:
    description: "Current app environment"
  cloudflare_zone_secret:
    description: "Cloudflare zone id secret name"
  should_deploy:
    description: "Telling if deploy should happen"
  dev_environment_to_deploy:
    description: "Dev environment to deploy"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'settings'
  color: 'white'
