name: 'test-delete'
on: # rebuild any PRs and main branch changes
  delete:
    branches:
      - dev/**

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: variables-output
        with:
          app_key: "trustup-io-website-monitoring"
          github_branch: "${{ github.event.ref }}"
      - run: |
          echo doppler_app_service_token_secret: ${{ steps.variables-output.outputs.doppler_app_service_token_secret }}
          echo trustup_app_key: ${{ steps.variables-output.outputs.trustup_app_key }}
          echo trustup_app_key_suffix: ${{ steps.variables-output.outputs.trustup_app_key_suffix }}
          echo trustup_app_key_suffixed: ${{ steps.variables-output.outputs.trustup_app_key_suffixed }}
          echo dev_environment_to_deploy: ${{ steps.variables-output.outputs.dev_environment_to_deploy }}
          echo app_url: ${{ steps.variables-output.outputs.app_url }}
          echo app_environment: ${{ steps.variables-output.outputs.app_environment }}
          echo cloudflare_zone_secret: ${{ steps.variables-output.outputs.cloudflare_zone_secret }}
          echo should_deploy: ${{ steps.variables-output.outputs.should_deploy }}