name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - release/**
      - dev/**

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-production: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: variables-output
        with:
          app_key: "trustup-io-website-monitoring"
          github_branch: "${{ github.ref }}"
      - run: |
          echo {{ steps.variables-output.trustup_app_key }}
          echo {{ steps.variables-output.trustup_app_key_suffixed }}